### ISSUE TITLE
Crashes on DM

### ISSUE THREAD

**Issue by YorkAARGH** [An-Idiots-Guide/guidebot#13]
Since moving to the new friendly permission levels, when you DM the bot a command it crashes with the following error
```
Uncaught Exception:  TypeError: Cannot read property 'owner' of null
    at Object.check (C:\Users\YorkAARGH\Documents\GitHub\guidebot\config.js:45:40)
    at Client.client.permlevel.message [as permlevel] (C:\Users\YorkAARGH\Documents\GitHub\guidebot\modules\functions.js:19:24)
    at module.exports (C:\Users\YorkAARGH\Documents\GitHub\guidebot\events\message.js:32:24)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:288:17)
    at WebSocket.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\ws\lib\EventTarget.js:103:16)
```

@eslachance 
Steps to reproduce:
1) Download latest code and run it
2) DM the bot a command.

This also applies to the [class-based](https://github.com/An-Idiots-Guide/guidebot/tree/class-based) branch.

**Comment by eslachance** [comment]
Darnit I forgot to account for that when I rewrote for friendly permissions.

**Comment by YorkAARGH** [comment]
Still crashes in both master and class-based
```
Uncaught Exception:  TypeError: Cannot read property 'owner' of null
    at Object.check (C:\Users\YorkAARGH\Documents\GitHub\guidebot\config.js:48:40)
    at Client.client.permlevel.message [as permlevel] (C:\Users\YorkAARGH\Documents\GitHub\guidebot\modules\functions.js:20:24)
    at module.exports (C:\Users\YorkAARGH\Documents\GitHub\guidebot\events\message.js:32:24)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:288:17)
    at WebSocket.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\ws\lib\EventTarget.js:103:16)
```

The line in question is this one `check: (message) => message.guild.owner.user.id === message.author.id` when it checks for a guild owner.
