### ISSUE TITLE
Help Stopped Working..?

### ISSUE THREAD

**Issue by Nyctara** [An-Idiots-Guide/guidebot#26]
So the bot's been running fine for awhile, then i used the help command and everything stopped working.. any ideas?

Uncaught Exception:  TypeError: Cannot read property 'permLevel' of undefined
    at message.guild.client.commands.filter.cmd (C:\Users\Name\Desktop\guidebot\commands\help.js:16:97)
    at Map.filter (C:\Users\Name\Desktop\guidebot\node_modules\enmap\src\index.js:254:11)
    at Object.exports.run (C:\Users\Name\Desktop\guidebot\commands\help.js:16:56)
    at module.exports (C:\Users\Name\Desktop\guidebot\events\message.js:66:7)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\Name\Desktop\guidebot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Name\Desktop\guidebot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Name\Desktop\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\Name\Desktop\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)

**Comment by nathanielcwm** [comment]
idk ive got the same problem but it is with propercase
2017-11-01T10:51:24.895903+00:00 app[worker.1]: Uncaught Exception:  TypeError: Cannot read property 'toProperCase' of undefined

2017-11-01T10:51:24.895905+00:00 app[worker.1]:     at sorted.forEach.c (/app/commands/help.js:19:35)

2017-11-01T10:51:24.895906+00:00 app[worker.1]:     at Array.forEach (<anonymous>)

2017-11-01T10:51:24.895907+00:00 app[worker.1]:     at Object.exports.run (/app/commands/help.js:18:12)

2017-11-01T10:51:24.895907+00:00 app[worker.1]:     at module.exports (/app/events/message.js:66:7)

2017-11-01T10:51:24.895908+00:00 app[worker.1]:     at emitOne (events.js:116:13)

2017-11-01T10:51:24.895908+00:00 app[worker.1]:     at Client.emit (events.js:211:7)

2017-11-01T10:51:24.895911+00:00 app[worker.1]:     at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)

2017-11-01T10:51:24.895913+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)

2017-11-01T10:51:24.895914+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)

2017-11-01T10:51:24.895914+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)

**Comment by Excigma** [comment]
@Nyctara, Please ask this in the An Idiot's Guilde guild, and you can get your answer faster.
Invite link: : https://discord.gg/gkZCQtH
Also we cannot help unless we see your code. 

Quick help:
`Cannot read property 'permLevel' of undefined`:
You are doing `<something>.permLevel` and `something` is undefined.

`at message.guild.client.commands.filter.cmd (C:\Users\Name\Desktop\guidebot\commands\help.js:16:97)`
It says EXACTLY where it is. I wonder what `16:97` is Line: 16, Character 97.
If you are using a proper code editor like Atom or VScode:

![image](https://user-images.githubusercontent.com/30280397/32341144-8a2ae28a-c061-11e7-977b-036395842adc.png)

You can see it.^

More help, go to the Discord server.

**Comment by YorkAARGH** [comment]
Closed due to no response, assumed issue is fixed.
