### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by hrtrd** [An-Idiots-Guide/guidebot#59]
hello, new installation.  read guide, in config.js  add ownerid and token, try start got that: 

node index.js
/home/neoll/guidebot/index.js:9
const { promisify } = require("util");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by kyranet** [comment]
You're using an ancient version of Node.js, probably before Cretaceous, you need at least node.js 8.
