### ISSUE TITLE
Bot isn't responding to DMs

### ISSUE THREAD

**Issue by bradam12** [An-Idiots-Guide/guidebot#64]
After upgrading and migrating to enmap v4 using the latest commits, I noticed I couldn't DM the bot anymore.

`TypeError: Cannot read property 'id' of null
    at module.exports (/var/nodejs/guidebot/events/message.js:12:72)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/var/nodejs/guidebot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/var/nodejs/guidebot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/var/nodejs/guidebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/var/nodejs/guidebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/var/nodejs/guidebot/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)`

This led me to [message.js](https://github.com/AnIdiotsGuide/guidebot/blob/master/events/message.js#L12).  `message.guild.id` was null, obviously since it was a DM.
`const settings = message.settings = client.getSettings(message.guild.id);`

It might not be the prettiest solution, and I'm totally not ruling out something wrong on my end, but this worked for me.
`const settings = message.settings = client.getSettings(message.guild ? message.guild.id : "");`

**Comment by YorkAARGH** [comment]
@eslachance possible oversight?

**Comment by BlueWoIf** [comment]
Kuki
