### ISSUE TITLE
`make` error

### ISSUE THREAD

**Issue by dndrheadof** [An-Idiots-Guide/guidebot#71]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dndrhead/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/home/dndrhead/.nvm/versions/node/v11.7.0/bin/node" "/home/dndrhead/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dndrhead/guidebot/node_modules/leveldown
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dndrhead/.npm/_logs/2019-01-18T15_03_39_809Z-debug.log

```
Any ideas?
Node version: 11.7.0
Npm version: 6.5.0

**Comment by dndrheadof** [comment]
gudiebot-class version works perfectly
but this won't work for me

**Comment by eslachance** [comment]
Please run `sudo apt-get install build-essential` on your system, and also ensure that Python 2.7 is installed and is the default python version (this should usually be the case in most popular Linux systems including Ubuntu).

**Comment by eslachance** [comment]
no update or follow-up.
