### ISSUE TITLE
Unable to respond to DMs

### ISSUE THREAD

**Issue by MarcTowler** [An-Idiots-Guide/guidebot#76]
Similar issue to #64 where I am getting the following error when a user responds to a DM sent by the bot:

`Uncaught Promise Error:  TypeError: Cannot read property 'me' of undefined
    at module.exports.run (C:\Users\MarcT\WebstormProjects\Discord-Bot\events\message.js:17:55)
    at Bot.client.on.args (C:\Users\MarcT\WebstormProjects\Discord-Bot\index.js:191:45)
    at Bot.emit (events.js:159:13)
    at MessageCreateHandler.handle (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\discord.js\src\client\websocket\
packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\discord.js\src\client\websocke
t\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\discord.js\src\client\websocket
\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\discord.js\src\client\websocke
t\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:159:13)
    at Receiver._receiver.onmessage (C:\Users\MarcT\WebstormProjects\Discord-Bot\node_modules\ws\lib\websocket.js:137:47)`

Which refers to the following:
`// Cancel any attempt to execute commands if the bot cannot respond to the user.
    if (!message.channel.permissionsFor(message.guild.me).missing("SEND_MESSAGES")) return;
`
If I step pass this by commenting it out, the bot is then left in a state where it is unable to respond to the user, leaving no error behind either.

**Comment by AndrewJWin** [comment]
This is likely fixed by PR #64, however until the PR is fully reviewed and accepted. This issue may persist.

**Comment by AndrewJWin** [comment]
@YorkAARGH This Issue has been left since 2/12/19, the PR request that was to fix the issue has been closed. I suggest closing the issue.
