### ISSUE TITLE
New Extend Class

### ISSUE THREAD

**Issue by BannukDE** [An-Idiots-Guide/guidebot#9]
https://github.com/An-Idiots-Guide/guidebot/blob/aea9b10cb53959748a763a530dc6b4595b950d2d/index.js#L46

shouldn't it be:
if (message.author.id === this.config.ownerID) return 10; ?

**Comment by YorkAARGH** [comment]
That is a weird one, I use this code in production and I've had no
problems, when I get chance I'll look into it

**Comment by YorkAARGH** [comment]
Alright, I did some tests and ran both the current code and `this.client` and these are the results

Running it with the code as is, works as intended, in my example I put myself as the bot owner and it returned the correct level [picture 1](http://evie.ban-hammered.me/i/9i47x.png)

prefixing `client.config.ownerID` with `this.` resulted in the following crash when issuing the `-mylevel` command a second time.

```
Uncaught Exception:  TypeError: Cannot read property 'config' of undefined
    at GuideBot.permlevel (C:\Users\YorkAARGH\Documents\GitHub\guidebot\index.js:46:42)
    at module.exports (C:\Users\YorkAARGH\Documents\GitHub\guidebot\events\message.js:32:24)
    at emitOne (events.js:115:13)
    at GuideBot.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:288:17)
    at WebSocket.onMessage (C:\Users\YorkAARGH\Documents\GitHub\guidebot\node_modules\ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:125:13)
```
and if I remember correctly the `this` keyword is only for the constructor? I dunno, but it's pretty clear that it works as intended without the `this` keyword.

**Comment by BannukDE** [comment]
why prefixig? replacing
I am not a native english speaker so maybe I just missunderstand.
I run the code with this.config fine but do not use your rest of botcode...

What if someone would rename "client" to "bot" in the rest of the code right from:
const client = new GuideBot(); to const bot = new GuideBot();
then the class GuideBot would not find client as a var or?

What I mean is if someone would create a new GuideBot() client would be undefined?
@YorkAARGH
